add missing libvndfwk_detect_jni.qti_vendor
11-09 20:51:04.646  4153  6059 E AndroidRuntime: FATAL EXCEPTION: NativeReceiver
11-09 20:51:04.646  4153  6059 E AndroidRuntime: Process: .qtidataservices, PID: 4153
11-09 20:51:04.646  4153  6059 E AndroidRuntime: java.lang.NoClassDefFoundError: com.qualcomm.qti.VndFwkDetect
11-09 20:51:04.646  4153  6059 E AndroidRuntime: 	at com.qualcomm.qti.cne.relay.WlanStaInfoRelay$CountryCodeRetriever.getIsVendorEnhancedFramework(WlanStaInfoRelay.java:727)
11-09 20:51:04.646  4153  6059 E AndroidRuntime: 	at com.qualcomm.qti.cne.relay.WlanStaInfoRelay$CountryCodeRetriever.retrieveCountryCode(WlanStaInfoRelay.java:792)
11-09 20:51:04.646  4153  6059 E AndroidRuntime: 	at com.qualcomm.qti.cne.relay.WlanStaInfoRelay$4.onCommand(WlanStaInfoRelay.java:255)
11-09 20:51:04.646  4153  6059 E AndroidRuntime: 	at com.qualcomm.qti.cne.hwinterface.NativeHalServerCallback$CommandWrapper.handleMessage(NativeHalServerCallback.java:247)
11-09 20:51:04.646  4153  6059 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-09 20:51:04.646  4153  6059 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:248)
11-09 20:51:04.646  4153  6059 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:338)
11-09 20:51:04.646  4153  6059 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:85)
11-09 20:51:04.646  4153  6059 E AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libvndfwk_detect_jni.qti_vendor.so" not found
11-09 20:51:04.646  4153  6059 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1090)
11-09 20:51:04.646  4153  6059 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
11-09 20:51:04.646  4153  6059 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1765)
11-09 20:51:04.646  4153  6059 E AndroidRuntime: 	at com.qualcomm.qti.VndFwkDetect.<clinit>(VndFwkDetect.java:40)
11-09 20:51:04.646  4153  6059 E AndroidRuntime: 	... 8 more